Repository bsv-blockchain/go-wallet-toolbox, pull requests merged in 2025-07, with the labels that each got.

#320 [FEATURE] WalletServices: add MerklePath method to Bitails service
  examples/services_markle_path/services_markle_path.go
  infra-config.example.yaml
  pkg/defs/services.go
  pkg/internal/testabilities/testservices/bitails_fixture.go
  pkg/internal/txutils/proof_for_merkle_path.go
  pkg/internal/txutils/proof_for_merkle_path_test.go
  pkg/services/internal/bitails/broadcast.go
  pkg/services/internal/bitails/constants.go
  pkg/services/internal/bitails/fetch_tx_info.go
  pkg/services/internal/bitails/merkle_path.go
  pkg/services/internal/bitails/merkle_path_test.go
  pkg/services/internal/bitails/testabilities/constants.go
  pkg/services/internal/bitails/testabilities/fixture.go
  pkg/services/internal/bitails/testabilities/utils.go
  pkg/services/internal/bitails/utils.go
  pkg/services/internal/whatsonchain/merkle_path.go
  pkg/services/internal/whatsonchain/merkle_path_test.go
  pkg/services/services.go
  pkg/services/services_get_merkle_path_test.go
Labels: feature, [feature]

#347 fix: rpc params logging have always error in first param
  pkg/internal/logging/test_writer.go
  pkg/storage/internal/server/tracer.go
  pkg/storage/internal/server/tracer_test.go
Labels: tested

#363 [FEATURE] WalletServices: create findChainTipHeader (bitails)
  examples/internal/show/show.go
  examples/services_examples/find_chain_tip_header/find_chain_tip_header.go
  examples/services_examples/height/height.go
  pkg/internal/testabilities/testservices/fixture_bitails.go
  pkg/internal/testabilities/testservices/fixture_services.go
  pkg/services/internal/arc/arc_service.go
  pkg/services/internal/arc/testabilities/fixture_arc.go
  pkg/services/internal/bhs/service.go
  pkg/services/internal/bhs/testabilities/fixture.go
  pkg/services/internal/bitails/current_height.go
  pkg/services/internal/bitails/current_height_test.go
  pkg/services/internal/bitails/fetch_tx_info.go
  pkg/services/internal/bitails/helpers.go
  pkg/services/internal/bitails/merkle_path.go
  pkg/services/internal/bitails/merkle_path_test.go
  pkg/services/internal/bitails/service.go
  pkg/services/internal/bitails/service_test.go
  pkg/services/internal/bitails/utils.go
  pkg/services/services.go
  pkg/services/services_find_chain_tip_header_test.go
Labels: feature, tested

#350 Feat(#342)config generator for example setup
  .gitignore
  examples/internal/example_setup/examples-config-example.yaml
  examples/internal/example_setup/load_config.go
  examples/internal/example_setup/setup.go
Labels: tested

#394 [FEATURE] WalletService: create missing RawTx in providers
  examples/internal/show/show.go
  examples/services_examples/raw_tx/raw_tx.go
  pkg/internal/testabilities/testservices/fixture_bitails.go
  pkg/services/internal/bitails/service.go
  pkg/services/internal/bitails/service_test.go
  pkg/services/internal/bitails/utils.go
  pkg/services/services.go
  pkg/services/services_current_height_test.go
  pkg/services/services_rawtx_test.go
Labels: feature, tested

#411 [FEATURE] WalletServices: create getScriptHashHistory method missing in providers
  examples/internal/show/show.go
  examples/services_examples/serivcies_is_valid_root/is_valid_root_for_height.go
  examples/services_examples/services_current_height/current_height.go
  examples/services_examples/services_find_chain_tip_header/find_chain_tip_header.go
  examples/services_examples/services_raw_tx/raw_tx.go
  examples/services_examples/services_script_hash_history/script_hash_history.go
  infra-config.example.yaml
  pkg/defs/bitails.go
  pkg/defs/services.go
  pkg/internal/testabilities/testservices/fixture_bitails.go
  pkg/services/internal/bitails/helpers.go
  pkg/services/internal/bitails/internal/dto/script_hash_history.go
  pkg/services/internal/bitails/script_history_test.go
  pkg/services/internal/bitails/service.go
  pkg/services/internal/bitails/utils.go
  pkg/services/services.go
  pkg/services/services_get_script_history_test.go
Labels: feature, tested
